### ISSUE TITLE
Map not showing up in Demos

### ISSUE THREAD

**Issue by bdaunt** [jumpinjackie/cesium-dotnet-examples#1]
I'm new to Cesium development. I just ran your demos out of the box. Each one ran without a problem except that the actual map does not appear in any of them. I'm attached a screenshot of the Hello World. I've tried on several different systems (32 and 64 bit) and different browsers. There must be something very obvious that I am missing but I can't see it. Any help would be greatly appreciated.
![cesiumnet](https://cloud.githubusercontent.com/assets/2333943/16178771/aeb63e88-361f-11e6-8be3-e66d5853bc78.png)

**Comment by jumpinjackie** [comment]
You probably have to supply your own BingMaps API key as Cesium's default one has been abused beyond its intended use.

**Comment by bdaunt** [comment]
Ah of course! I knew it was something too simple - thanks! Great work BTW!

**Comment by jumpinjackie** [comment]
I've updated the examples to use OSM/Stamen as the default base layer setup
